INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    #'authentication',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    "authentication",
    "drf_spectacular",
]