# Generated by Django 6.0.2 on 2026-03-03 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Разрешены только буквы, цифры, подчеркивания и точки.",
                        regex="^[a-zA-Z0-9_.]+$",
                    )
                ],
            ),
        ),
    ]
