# Generated by Django 6.0.2 on 2026-03-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcodemodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailVerificationModel',
        ),
        migrations.DeleteModel(
            name='PasswordResetCodeModel',
        ),
    ]
